---
- hosts: SonarQubeServer
  become: true
  tasks:
    - name: Install java
      yum:
        name: java-11-openjdk
        state: present
    - name: get sonarqube url
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.1.0.47736.zip
        dest: /tmp/
    - name: copy the sonarqube url 
      copy:
        src: /tmp/sonarqube-9.1.0.47736.zip 
        dest: /usr/local/   
    
    - name: Unpacking the archive
      unarchive:
        src: /usr/local/sonarqube
        dest: /usr/local/
        remote_src: yes
    - name: adding user 
      user: 
        name: sonar
    - name: adding visudo
      lineinfile:
        path: /etc/sudoers
        line: 'sonar ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        state: present
          
...
